### ISSUE TITLE
ntpd doesnt see PPS

### ISSUE THREAD

**Issue by Aptahar** [OpenNuvoton/buildroot_2024#3]
ntpd compiled in buildroot doesn't work with /dev/pps0. 
In log there is error from ntpd:
`ntpd[1080]: refclock_newpeer: clock type 22 invalid`
Internet says that ntpd needs --ATOM_PPS option and timepps.h from ppstools when compiling it
`ppstest /dev/pps0` works

**Comment by Aptahar** [comment]
Also ntpq and ntpdc utils compiled but not installed in target fs by buildroot

**Comment by ychuang3** [comment]
Do you "make menuconfig" in buildroot?
Please read the MA35D1 buildroot user manual.

**Comment by Aptahar** [comment]
Chip is nuc980.
"make menuconfig" is done, system is working.
My ntp.conf:
server 127.127.22.0 minpoll 1
fudge 127.127.22.0 refid PPS stratum 0 flag1 1 flag3 1
server 127.127.20.0 mode 81 minpoll 4 prefer
fudge 127.127.20.0 refid NMEA stratum 1 flag1 0

And NMEA time is working

**Comment by Aptahar** [comment]
[buildroot_config.zip](https://github.com/user-attachments/files/17842595/buildroot_config.zip)

**Comment by Aptahar** [comment]
ntpd packadge ./configure script check /sys/timepps.h file existence on host and if it isn't there, then build would be without support of PPS.
File /sys/timepps.h appears with pps-tools installed on host
